server:
  port: 8009
  tomcat:
    uri-encoding: "utf-8"

mybatis:
  type-aliases-package: "com.superbug.jvm.po"
  mapper-locations: "classpath:mybatis-sql/*.xml"

spring:
  datasource:
    url: "jdbc:mysql://120.77.37.94:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false"
    data-username: "root"
    data-password: "123456"
    driver-class-name: com.mysql.jdbc.Driver

  rabbitmq:
    host: "120.77.37.94"
    port: 5672
    username: "root"
    password: "123456"
    publisher-confirms: true
    virtual-host: "/"
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: "5000ms"
          #max-interval:
        default-requeue-rejected: false
